version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'dev'
  - package-ecosystem: npm
    directory: '/server'
    schedule:
      interval: 'daily'
    target-branch: 'dev'
  - package-ecosystem: npm
    directory: '/client'
    schedule:
      interval: 'daily'
    target-branch: 'dev'
  - package-ecosystem: npm
    directory: '/infra'
    schedule:
      interval: 'daily'
    target-branch: 'dev'
