version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"
  - package-ecosystem: npm
    directory: "/server"
    schedule:
      interval: "monthly"
    target-branch: "dev"
  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: "monthly"
    target-branch: "dev"
  - package-ecosystem: npm
    directory: "/infra"
    schedule:
      interval: "monthly"
    target-branch: "dev"