name: test

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Check licenses
        run: yarn licenses:check

      - name: Linting
        run: yarn lint

      - name: Prettier
        run: yarn format

      - name: Compile
        run: yarn check-types

  e2e:
    runs-on: ubuntu-latest
    needs: test
    env:
      FCLI_TLS_PATH: "$GITHUB_WORKSPACE/e2e-env/config/cert/"
      FCLI_SERVER: "localhost:50052"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Install cli
        run: |
          curl https://raw.githubusercontent.com/findy-network/findy-agent-cli/HEAD/install.sh > install.sh
          chmod a+x install.sh
          sudo ./install.sh -b /bin

      - name: Start env
        run: |
          cd e2e-env
          docker-compose up -d

      - name: Start frontend
        run: |
          yarn
          REACT_APP_HOST_BACKEND=http://localhost:5001 REACT_APP_HOST_WEBSOCKET=ws://localhost:5001 yarn client:start &

      - name: Cypress run
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          browser: chrome
